In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
fire=pd.read_csv("fire.csv")

In [3]:
fire.head()

# Latitude   Longitude   COTotalColumn  COMixingRatio surface  \
0     9.03868    -20.8853    2.579390e+18                134.620   
1     8.81834    -20.8535    2.650670e+18                139.292   
2     8.59805    -20.8216    2.754350e+18                158.140   
3     8.37733    -20.7898    2.720380e+18                148.004   
4     8.99296    -21.3651    2.507630e+18                134.441   

   COMixingRatio 900hPa  COMixingRatio 800hPa  COMixingRatio 700hPa  \
0               173.135               153.868               124.655   
1               183.707               164.003               131.822   
2               233.699               217.127               165.104   
3               196.613               175.510               138.600   
4               179.879               166.433               134.634   

   COMixingRatio 600hPa   COMixingRatio 500hPa  COMixingRatio 400hPa  \
0               114.139                106.779              109.7300   
1               120.366                110.927              110.9010   
2               135.990                106.739               85.2269   
3               125.555                113.432              110.0860   
4               119.701                106.467               99.5474   

   COMixingRatio 300hPa  COMixingRatio 200hPa  COMixingRatio 100hPa  \
0              122.0820              122.0620               53.1248   
1              118.1920              115.0210               51.7430   
2               71.4620               69.4771               42.9896   
3              112.1170              106.2790               50.0490   
4               96.0743               91.8761               47.7643   

   RetrievedSurfaceTemperature   
0                       300.221  
1                       300.686  
2                       300.940  
3                       301.036  
4                       300.325

In [4]:
fire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214868 entries, 0 to 214867
Data columns (total 14 columns):
# Latitude                      214868 non-null float64
 Longitude                      214868 non-null float64
 COTotalColumn                  214868 non-null float64
COMixingRatio surface           214868 non-null float64
COMixingRatio 900hPa            179518 non-null float64
COMixingRatio 800hPa            188607 non-null float64
COMixingRatio 700hPa            197725 non-null float64
COMixingRatio 600hPa            214027 non-null float64
 COMixingRatio 500hPa           214868 non-null float64
COMixingRatio 400hPa            214868 non-null float64
COMixingRatio 300hPa            214868 non-null float64
COMixingRatio 200hPa            214868 non-null float64
COMixingRatio 100hPa            214868 non-null float64
RetrievedSurfaceTemperature     214868 non-null float64
dtypes: float64(14)
memory usage: 23.0 MB


In [5]:
fire.describe()

# Latitude      Longitude   COTotalColumn  COMixingRatio surface  \
count  214868.000000  214868.000000    2.148680e+05          214868.000000   
mean       -2.670918      13.926136    1.518038e+18             101.285630   
std        44.750644     102.821648    5.794790e+17              69.869174   
min       -84.982600    -179.998000    1.945910e+17              17.786300   
25%       -31.696625     -79.431250    1.171618e+18              52.703600   
50%        -0.458235      27.977450    1.555715e+18              87.764500   
75%        28.540350      99.425275    1.906960e+18             128.032000   
max        84.783500     179.997000    7.193360e+18            2425.250000   

       COMixingRatio 900hPa  COMixingRatio 800hPa  COMixingRatio 700hPa  \
count         179518.000000         188607.000000         197725.000000   
mean              96.702860             89.508774             83.692415   
std               50.871879             38.431443             32.798902   
min               25.557100             21.293200             18.602200   
25%               57.112550             60.191150             58.948800   
50%               88.025250             79.912100             77.217600   
75%              123.952250            113.408000            105.404000   
max             2100.800000           1192.090000            710.467000   

       COMixingRatio 600hPa   COMixingRatio 500hPa  COMixingRatio 400hPa  \
count         214027.000000          214868.000000         214868.000000   
mean              76.558943              73.177397             73.531732   
std               31.860346              28.077525             29.205367   
min               13.907700              13.889800             13.040000   
25%               55.912300              56.029250             58.304875   
50%               73.091900              71.874100             74.188150   
75%               95.187650              89.511000             88.572500   
max             2065.610000            1222.940000            929.544000   

       COMixingRatio 300hPa  COMixingRatio 200hPa  COMixingRatio 100hPa  \
count         214868.000000         214868.000000         214868.000000   
mean              73.586831             61.807356             34.259115   
std               28.401448             31.450767             15.471465   
min               12.077800              9.193550              9.420420   
25%               58.401425             40.625825             18.618400   
50%               75.175650             60.511000             34.552200   
75%               87.061225             77.822600             47.859625   
max              692.958000            719.241000            129.150000   

       RetrievedSurfaceTemperature   
count                 214868.000000  
mean                     281.336646  
std                       25.646615  
min                      195.511000  
25%                      259.203000  
50%                      293.318000  
75%                      300.533000  
max                      341.098000

In [6]:
fire.isnull().sum()

# Latitude                          0
 Longitude                          0
 COTotalColumn                      0
COMixingRatio surface               0
COMixingRatio 900hPa            35350
COMixingRatio 800hPa            26261
COMixingRatio 700hPa            17143
COMixingRatio 600hPa              841
 COMixingRatio 500hPa               0
COMixingRatio 400hPa                0
COMixingRatio 300hPa                0
COMixingRatio 200hPa                0
COMixingRatio 100hPa                0
RetrievedSurfaceTemperature         0
dtype: int64

In [7]:
from sklearn import preprocessing
scalar=preprocessing.StandardScaler()

In [8]:
fire.drop('COMixingRatio 900hPa',axis=1,inplace=True)

In [9]:
fire.drop('COMixingRatio 800hPa',axis=1,inplace=True)

In [10]:
fire.drop('COMixingRatio 700hPa',axis=1,inplace=True)

In [11]:
fire.drop('COMixingRatio 600hPa',axis=1,inplace=True)

In [12]:
fire.drop(' COMixingRatio 500hPa',axis=1,inplace=True)

In [13]:
fire.drop('COMixingRatio 400hPa',axis=1,inplace=True)

In [14]:
fire.drop('COMixingRatio 300hPa',axis=1,inplace=True)

In [15]:
fire.drop('COMixingRatio 200hPa',axis=1,inplace=True)

In [16]:
fire.drop('COMixingRatio 100hPa',axis=1,inplace=True)

In [17]:
X=fire
fire.head()

# Latitude   Longitude   COTotalColumn  COMixingRatio surface  \
0     9.03868    -20.8853    2.579390e+18                134.620   
1     8.81834    -20.8535    2.650670e+18                139.292   
2     8.59805    -20.8216    2.754350e+18                158.140   
3     8.37733    -20.7898    2.720380e+18                148.004   
4     8.99296    -21.3651    2.507630e+18                134.441   

   RetrievedSurfaceTemperature   
0                       300.221  
1                       300.686  
2                       300.940  
3                       301.036  
4                       300.325

In [18]:
y=fire.iloc[:,2:].values

In [19]:
y

array([[2.57939e+18, 1.34620e+02, 3.00221e+02],
       [2.65067e+18, 1.39292e+02, 3.00686e+02],
       [2.75435e+18, 1.58140e+02, 3.00940e+02],
       ...,
       [2.03171e+18, 8.45694e+01, 3.29450e+02],
       [1.78954e+18, 8.49521e+01, 3.28098e+02],
       [1.66315e+18, 1.82100e+02, 3.33050e+02]])

In [20]:
temp=preprocessing.StandardScaler().fit(y).transform(y)

In [21]:
temp.shape

(214868, 3)

In [22]:
fire1=pd.DataFrame(temp,columns=['COTotalColumn','COMixingRatio surface','Temperature'])

In [23]:
y1=fire.iloc[:,:2].values

In [24]:
fire2=pd.DataFrame(y1,columns=['Latitude','Longitude'])

In [27]:
fire_Hazard=pd.concat([fire2,fire1],axis=1)
fire_Hazard

Latitude  Longitude  COTotalColumn  COMixingRatio surface  Temperature
0        9.03868   -20.8853       1.831568               0.477098     0.736331
1        8.81834   -20.8535       1.954575               0.543966     0.754462
2        8.59805   -20.8216       2.133495               0.813728     0.764366
3        8.37733   -20.7898       2.074873               0.668657     0.768109
4        8.99296   -21.3651       1.707732               0.474536     0.740386
5        8.77897   -21.3341       2.045519               0.575038     0.710402
6        8.56504   -21.3032       2.047883               0.610848     0.720539
7        8.35070   -21.2723       1.917369               0.618219     0.746196
8        9.11154   -21.1948       1.604363               0.425101     0.719097
9        9.16618   -20.9539       1.705178               0.308454     0.740347
10       9.35390   -21.4684       1.777157               0.449403     0.687942
11       9.13957   -21.4374       1.667713               0.419991     0.704202
12      18.41930   -29.2321       0.080353              -0.125120     0.596390
13      18.48430   -28.9838       0.102769              -0.058000     0.579351
14      18.80210   -27.0014       0.333184               0.025109     0.535836
15      19.33110   -27.9743       0.056814              -0.006450     0.563832
16      19.29230   -28.4343      -0.126713              -0.071284     0.579624
17      19.08310   -28.3979       0.051930              -0.028925     0.568862
18      19.25030   -28.9168      -0.069196              -0.080045     0.586486
19      19.03580   -28.8788       0.088964              -0.030848     0.573151
20      19.20350   -29.4279       0.031636              -0.128793     0.598730
21      18.98250   -29.3883       0.060524              -0.114134     0.596897
22      18.76130   -29.3497       0.112813              -0.064889     0.589372
23      18.53960   -29.3121       0.109327              -0.122211     0.598106
24      19.26810   -29.1784       0.018072              -0.122379     0.597092
25      19.05050   -29.1396       0.037624              -0.120370     0.598457
26      18.83280   -29.1018       0.067841              -0.078643     0.590113
27      18.61460   -29.0649       0.231040              -0.028839     0.569603
28      19.36730   -28.6903      -0.069420              -0.163376     0.603253
29      19.15570   -28.6531       0.025424              -0.143977     0.604189
...          ...        ...            ...                    ...          ...
214838 -29.80370   151.7290       0.806903               0.809348     1.486295
214839 -29.60210   151.7700       1.414640               0.582438     1.529225
214840 -29.40020   151.8100       2.257503               0.125998     1.698332
214841 -29.96240   151.2060       1.412397              -0.377616     1.762122
214842 -29.75840   151.2480       0.645776              -0.056299     1.958172
214843 -29.55440   151.2900      -0.238521               0.289776     1.776549
214844 -29.35010   151.3310       1.019284               0.594647     1.679811
214845 -29.91460   150.7100       0.415862              -0.036075     1.817802
214846 -29.70720   150.7530       0.394118               0.134986     1.848761
214847 -29.49980   150.7960       0.518419               0.147997     1.942185
214848 -29.29210   150.8390       1.571575              -0.242825     1.893056
214849 -29.86380   150.1920       0.339603               0.211515     1.893952
214850 -29.65190   150.2370       0.408320               0.197332     1.809964
214851 -29.44020   150.2820       0.427959               0.441532     1.806416
214852 -29.22800   150.3270       1.008309              -0.326617     1.864202
214853 -29.80770   149.6480       0.521974               0.061850     1.873092
214854 -29.37280   149.7430       0.517608               0.052733     1.853323
214855 -29.56980   149.4080       0.594350               0.115292     1.893679
214856 -29.34910   149.4570       0.587775               0

In [30]:
fh=np.asarray(fire_Hazard)
X_train=[]
Y_train=[]
count=0
for column in fh:
    if column[4]>0.75 or column[3]>0.75 :
        Y_train.append(1)
        count=count+1
    else:
        Y_train.append(0)
    X_train.append(column)
    if count == 10:
        break
display(X_train,Y_train,len(Y_train))

[array([  9.03868   , -20.8853    ,   1.83156772,   0.47709806,
          0.73633102]),
 array([  8.81834   , -20.8535    ,   1.95457506,   0.54396604,
          0.75446211]),
 array([  8.59805   , -20.8216    ,   2.13349482,   0.81372798,
          0.76436597]),
 array([  8.37733   , -20.7898    ,   2.07487306,   0.66865651,
          0.76810917]),
 array([  8.99296   , -21.3651    ,   1.70773205,   0.47453612,
          0.74038615]),
 array([  8.77897   , -21.3341    ,   2.04551904,   0.57503847,
          0.71040161]),
 array([  8.56504   , -21.3032    ,   2.04788324,   0.61084834,
          0.72053943]),
 array([  8.3507    , -21.2723    ,   1.91736913,   0.61821927,
          0.74619589]),
 array([  9.11154   , -21.1948    ,   1.60436308,   0.42510076,
          0.71909674]),
 array([  9.16618   , -20.9539    ,   1.70517802,   0.30845391,
          0.74034715]),
 array([  9.3539    , -21.4684    ,   1.77715664,   0.44940338,
          0.68794246]),
 array([  9.13957   , -21.4374  

[0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


1206

In [35]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit (X_train, Y_train)
print ('Coefficients: ', regr.coef_)
print ('Intercept: ',regr.intercept_)

Coefficients:  [-0.00375847 -0.00084638 -0.05189482  0.47302739  0.01033906]
Intercept:  0.08001966824734895


In [36]:
Y=regr.predict(fire_Hazard)
Y

array([ 0.20196957,  0.2282052 ,  0.34742833, ..., -0.07674835,
       -0.05056673,  0.61884084])